### ISSUE TITLE
An error has occurred while processing your transaction\nTransaction Captured

### ISSUE THREAD

**Issue by kaushalsutharoc** [mage2pro/2checkout#4]
`{"0":"An error has occurred while processing your transaction\nTransaction Captured\n","1":"#0 \/app\/myuser\/vendor\/mage2pro\/checkout.com\/Method.php(516): Dfe\\CheckoutCom\\Method->leh(Object(Closure))\n#1 \/app\/myuser\/vendor\/mage2pro\/checkout.com\/Method.php(360): Dfe\\CheckoutCom\\Method->capturePreauthorized(Object(Magento\\Sales\\Model\\Order\\Payment\\Transaction\\Interceptor))\n#2 [internal function]: Dfe\\CheckoutCom\\Method->charge()\n#3 \/app\/myuser\/vendor\/mage2pro\/core\/Payment\/Method.php(156): call_user_func(Array)\n#4 \/app\/myuser\/vendor\/mage2pro\/core\/Payment\/Method.php(860): Df\\Payment\\Method->action('charge')\n#5 \/app\/myuser\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Operations\/CaptureOperation.php(82): Df\\Payment\\Method->capture(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), '609')\n#6 \/app\/myuser\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Processor.php(85): Magento\\Sales\\Model\\Order\\Payment\\Operations\\CaptureOperation->capture(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), Object(Magento\\Sales\\Model\\Order\\Invoice\\Interceptor))\n#7 \/app\/myuser\/vendor\/magento\/module-sales\/Model\/Order\/Payment.php(467): Magento\\Sales\\Model\\Order\\Payment\\Processor->capture(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), Object(Magento\\Sales\\Model\\Order\\Invoice\\Interceptor))\n#8 \/app\/myuser\/vendor\/magento\/module-sales\/Model\/Order\/Invoice.php(344): Magento\\Sales\\Model\\Order\\Payment->capture(Object(Magento\\Sales\\Model\\Order\\Invoice\\Interceptor))\n#9 \/app\/myuser\/vendor\/magento\/module-sales\/Model\/Order\/Invoice.php(618): Magento\\Sales\\Model\\Order\\Invoice->capture()\n#10 \/app\/myuser\/vendor\/mage2pro\/checkout.com\/Handler\/CustomerReturn.php(148): Magento\\Sales\\Model\\Order\\Invoice->register()\n#11 \/app\/myuser\/vendor\/mage2pro\/checkout.com\/Controller\/Index\/Index.php(35): Dfe\\CheckoutCom\\Handler\\CustomerReturn::p('pay_tok_c61f507...')\n#12 \/app\/myuser\/vendor\/mage2pro\/core\/Qa\/lib\/exception.php(81): Dfe\\CheckoutCom\\Controller\\Index\\Index->Dfe\\CheckoutCom\\Controller\\Index\\{closure}()\n#13 \/app\/myuser\/vendor\/mage2pro\/checkout.com\/Controller\/Index\/Index.php(41): df_leh(Object(Closure))\n#14 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Dfe\\CheckoutCom\\Controller\\Index\\Index->execute()\n#15 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->___callParent('execute', Array)\n#16 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#17 \/app\/myuser\/generated\/code\/Dfe\/CheckoutCom\/Controller\/Index\/Index\/Interceptor.php(26): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->___callPlugins('execute', Array, Array)\n#18 \/app\/myuser\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->execute()\n#19 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->___callParent('dispatch', Array)\n#21 \/app\/myuser\/vendor\/magento\/module-customer-segment\/Model\/App\/Action\/ContextPlugin.php(81): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\CustomerSegment\\Model\\App\\Action\\ContextPlugin->aroundDispatch(Object(Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/app\/myuser\/app\/code\/mymagento\/StoreSwitcher\/Plugins\/ContextPlugin.php(138): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#24 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): mymagento\\StoreSwitcher\\Plugins\\ContextPlugin->aroundDispatch(Object(Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/app\/myuser\/generated\/code\/Dfe\/CheckoutCom\/Controller\/Index\/Index\/Interceptor.php(39): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->___callPlugins('dispatch', Array, Array)\n#27 \/app\/myuser\/vendor\/magento\/framework\/App\/FrontController.php(55): Dfe\\CheckoutCom\\Controller\\Index\\Index\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#29 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#30 \/app\/myuser\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#31 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/app\/myuser\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(69): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#33 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#34 \/app\/myuser\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#35 \/app\/myuser\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#36 \/app\/myuser\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#37 \/app\/myuser\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#38 \/app\/myuser\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#39 {main}","url":"\/dfe-checkout-com\/index\/index\/?cko-payment-token=pay_tok_c61f5076-904e-4086-b35d-2dddead43bf5","script_name":"\/index.php"}`

**Comment by kaushalsutharoc** [comment]
Hello?

**Comment by kaushalsutharoc** [comment]
I'm sorry, Posted by mistake.
