### ISSUE TITLE
compile error  mage 2.4.3

### ISSUE THREAD

**Issue by rydemods** [mage2pro/2checkout#8]
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 76.0 MiBPHP Fatal error:  Uncaught Error: Class 'Df\Core\OLegacy' not found in /home/cloudpanel/htdocs/local.mage/vendor/mage2pro/2checkout/LineItem.php:7
Stack trace:
#0 /home/cloudpanel/htdocs/local.mage/vendor/composer/ClassLoader.php(444): include()
#1 /home/cloudpanel/htdocs/local.mage/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/cloudpanel/htdocs/local.mage/vendor/mage2pro/2checkout/LineItem/Product.php(9): spl_autoload_call()
#4 /home/cloudpanel/htdocs/local.mage/vendor/composer/ClassLoader.php(444): include('/home/cloudpane...')
#5 /home/cloudpanel/htdocs/local.mage/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#7 [internal function]: spl_autoload_call()
#8 /home/cloudpanel/htdocs/local.mage/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScann in /home/cloudpanel/htdocs/local.mage/vendor/mage2pro/2checkout/LineItem.php on line 7

**Comment by rydemods** [comment]
running composer update seems to have pulled a newer. version and now compiles, closing this.
